import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card'
import { Button } from '@/components/ui/button'

export default function feedback() {
  const restartSia = () => {
    console.log('Restarting SIA')
    callAction({ name: 'restart_sia_action', payload: {} })
  }

  const positiveFeedback = () => {
    console.log('Positive feedback')
    callAction({ name: 'positive_feedback_action', payload: {} })
  }

  const negativeFeedback = () => {
    console.log('Negative feedback')
    callAction({ name: 'negative_feedback_action', payload: {} })
  }

  return (
    <Card className="w-1/2 max-w-sm">
      <CardHeader>
        <CardTitle className="text-sm">
          This content was generated by AI and may contain inaccuracies.
        </CardTitle>
      </CardHeader>
      <CardContent className="space-x-2">
        <Button id="restart_sia" variant="outline" onClick={restartSia}>
          🔄 - New SIA chat
        </Button>
        <Button
          id="positive_feedback"
          variant="outline"
          onClick={positiveFeedback}
        >
          👍
        </Button>
        <Button
          id="negative_feedback"
          variant="outline"
          onClick={negativeFeedback}
        >
          👎
        </Button>
      </CardContent>
    </Card>
  )
}
